// Fallback alignment used because this environment's egress policy blocks
// huggingface.co (and every model CDN), so the Whisper model in
// scripts/transcribe.mjs can't be downloaded here.
//
// We already have the exact narration (the user provided it per scene), so we
// only need timing. This detects real pauses in public/voiceover.wav with
// ffmpeg's silencedetect, snaps the four sentence boundaries to those pauses,
// and distributes each sentence's words across its span — producing:
//   - public/captions.json   word-level Caption[] for @remotion/captions
//   - src/sceneTiming.ts      per-scene frame durations synced to the voice
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

const cwd = process.cwd();
const FPS = 30;
const WAV = path.join(cwd, "public", "voiceover.wav");

// The four spoken lines, one per scene, exactly as narrated.
const SENTENCES = [
  "This isn't just showing up and working out. Here's what a real session looks like.",
  "First, we check how you move — mobility, strength, anything that needs attention.",
  "Then every rep gets watched, not just counted. Form corrected in real time.",
  "Progress gets logged, and the plan evolves as you get stronger. DM or WhatsApp to start.",
];

// --- 1. Probe duration + detect silences -------------------------------------
const ff = (args) => {
  try {
    return execSync(`npx remotion ffmpeg ${args} 2>&1`, { encoding: "utf8" });
  } catch (e) {
    // ffmpeg exits non-zero for a bare probe; its log still lands on stdout.
    return `${e.stdout ?? ""}${e.stderr ?? ""}`;
  }
};

const probe = ff(`-i ${WAV}`);
const durMatch = probe.match(/Duration:\s*(\d+):(\d+):([\d.]+)/);
const durationSec =
  Number(durMatch[1]) * 3600 + Number(durMatch[2]) * 60 + Number(durMatch[3]);

const sd = ff(`-i ${WAV} -af silencedetect=noise=-30dB:d=0.18 -f null -`);
const gaps = [];
let pendingStart = null;
for (const line of sd.split("\n")) {
  const s = line.match(/silence_start:\s*([\d.]+)/);
  const e = line.match(/silence_end:\s*([\d.]+)/);
  if (s) pendingStart = Number(s[1]);
  if (e && pendingStart !== null) {
    gaps.push({ start: pendingStart, end: Number(e[1]) });
    pendingStart = null;
  }
}

// --- 2. Snap the 3 interior sentence boundaries to the nearest pause ----------
const wordCount = SENTENCES.map((s) => s.trim().split(/\s+/).filter((w) => /[a-z0-9]/i.test(w)).length);
const totalWords = wordCount.reduce((a, b) => a + b, 0);
const cum = wordCount.reduce((acc, n) => (acc.push((acc.at(-1) ?? 0) + n), acc), []);

const SNAP_WINDOW = 1.3; // seconds
const boundaries = []; // seconds, length 3 (interior cuts)
for (let i = 0; i < SENTENCES.length - 1; i++) {
  const proportional = (durationSec * cum[i]) / totalWords;
  let best = null;
  for (const g of gaps) {
    const mid = (g.start + g.end) / 2;
    const d = Math.abs(mid - proportional);
    if (d <= SNAP_WINDOW && (best === null || d < best.d)) best = { d, cut: g.end };
  }
  boundaries.push(best ? best.cut : proportional);
}

// Scene spans in seconds, then cumulative frame durations (no rounding drift).
const cuts = [0, ...boundaries, durationSec];
const totalFrames = Math.round(durationSec * FPS);
const cumFrames = boundaries.map((b) => Math.round(b * FPS));
const sceneFrames = [];
let prev = 0;
for (const f of [...cumFrames, totalFrames]) {
  sceneFrames.push(f - prev);
  prev = f;
}

// --- 3. Word-level captions: spread each sentence across its span -------------
const captions = [];
const weightOf = (w) => {
  const letters = (w.match(/[a-z0-9]/gi) || []).length;
  const pause = /[.,]$/.test(w) ? 2 : 0; // brief hold on punctuation
  return Math.max(2, letters) + pause;
};

for (let i = 0; i < SENTENCES.length; i++) {
  const start = cuts[i];
  const end = cuts[i + 1];
  const words = SENTENCES[i]
    .trim()
    .split(/\s+/)
    .filter((w) => w !== "—"); // drop standalone dash tokens
  const weights = words.map(weightOf);
  const wSum = weights.reduce((a, b) => a + b, 0);
  let t = start;
  for (let j = 0; j < words.length; j++) {
    const dur = ((end - start) * weights[j]) / wSum;
    const startMs = Math.round(t * 1000);
    const endMs = Math.round((t + dur) * 1000);
    captions.push({
      text: (j === 0 ? "" : " ") + words[j],
      startMs,
      endMs,
      timestampMs: Math.round((startMs + endMs) / 2),
      confidence: null,
    });
    t += dur;
  }
}

fs.writeFileSync(
  path.join(cwd, "public", "captions.json"),
  JSON.stringify(captions, null, 2),
);

const timingTs = `// GENERATED by scripts/align.mjs — do not edit by hand.
// Scene frame durations synced to public/voiceover.mp3 (30fps).
export const FPS = ${FPS};
export const SCENE_FRAMES = [${sceneFrames.join(", ")}] as const;
export const TOTAL_FRAMES = ${totalFrames};
`;
fs.writeFileSync(path.join(cwd, "src", "sceneTiming.ts"), timingTs);

console.log("duration:", durationSec.toFixed(2), "s  totalFrames:", totalFrames);
console.log("interior cuts (s):", boundaries.map((b) => b.toFixed(2)).join(", "));
console.log("sceneFrames:", sceneFrames.join(", "));
console.log("captions:", captions.length, "words");
