// Derives per-scene durations + the frames where accent words are spoken, from
// public/voiceover.wav. Whisper (scripts/transcribe.mjs) is the intended path,
// but this sandbox's egress blocks huggingface.co and every model CDN, so we
// align the known transcript to real audio pauses instead: ffmpeg silencedetect
// gives sentence boundaries, and words are spread across each sentence by weight
// to time the accent flash-pops. Output: src/sync.ts.
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

const cwd = process.cwd();
const FPS = 30;
const WAV = path.join(cwd, "public", "voiceover.wav");

// The narration as actually recorded (one sentence per scene). The accent words
// below all occur here, so their spoken time is real even though the on-screen
// headline copy is authored separately.
const SENTENCES = [
  "This isn't just showing up and working out. Here's what a real session looks like.",
  "First, we check how you move — mobility, strength, anything that needs attention.",
  "Then every rep gets watched, not just counted. Form corrected in real time.",
  "Progress gets logged, and the plan evolves as you get stronger. DM or WhatsApp to start.",
];

// Which spoken word drives each scene's accent flash / footer / CTA landing.
const TARGETS = [
  { flash: "showing", footer: null, cta: null },
  { flash: "move", footer: null, cta: null },
  { flash: "watched", footer: "counted", cta: null },
  { flash: "evolves", footer: null, cta: "dm" },
];

const norm = (w) => w.toLowerCase().replace(/[^a-z0-9]/g, "");

const ff = (args) => {
  try {
    return execSync(`npx remotion ffmpeg ${args} 2>&1`, { encoding: "utf8" });
  } catch (e) {
    return `${e.stdout ?? ""}${e.stderr ?? ""}`;
  }
};

// --- duration + silence gaps -------------------------------------------------
const probe = ff(`-i ${WAV}`);
const d = probe.match(/Duration:\s*(\d+):(\d+):([\d.]+)/);
const durationSec = Number(d[1]) * 3600 + Number(d[2]) * 60 + Number(d[3]);

const sd = ff(`-i ${WAV} -af silencedetect=noise=-30dB:d=0.18 -f null -`);
const gaps = [];
let pending = null;
for (const line of sd.split("\n")) {
  const s = line.match(/silence_start:\s*([\d.]+)/);
  const e = line.match(/silence_end:\s*([\d.]+)/);
  if (s) pending = Number(s[1]);
  if (e && pending !== null) {
    gaps.push({ start: pending, end: Number(e[1]) });
    pending = null;
  }
}

// --- snap the 3 interior sentence boundaries to real pauses ------------------
const wc = SENTENCES.map((s) => s.trim().split(/\s+/).filter((w) => /[a-z0-9]/i.test(w)).length);
const totalWords = wc.reduce((a, b) => a + b, 0);
const cumW = wc.reduce((acc, n) => (acc.push((acc.at(-1) ?? 0) + n), acc), []);

const SNAP = 1.3;
const boundaries = [];
for (let i = 0; i < SENTENCES.length - 1; i++) {
  const prop = (durationSec * cumW[i]) / totalWords;
  let best = null;
  for (const g of gaps) {
    const mid = (g.start + g.end) / 2;
    const dist = Math.abs(mid - prop);
    if (dist <= SNAP && (best === null || dist < best.dist)) best = { dist, cut: g.end };
  }
  boundaries.push(best ? best.cut : prop);
}
const cuts = [0, ...boundaries, durationSec];

// --- per-word times, then locate the target words ----------------------------
const weightOf = (w) => Math.max(2, (w.match(/[a-z0-9]/gi) || []).length) + (/[.,]$/.test(w) ? 2 : 0);

const EXIT_DUR = 8;
const sceneSync = [];
let cumFrames = 0;
const cumFrameStops = [];

for (let i = 0; i < SENTENCES.length; i++) {
  const start = cuts[i];
  const end = cuts[i + 1];
  const durationInFrames =
    Math.round(end * FPS) - Math.round(start * FPS); // no rounding drift
  cumFrames += durationInFrames;
  cumFrameStops.push(cumFrames);

  const words = SENTENCES[i].trim().split(/\s+/).filter((w) => w !== "—");
  const weights = words.map(weightOf);
  const wSum = weights.reduce((a, b) => a + b, 0);

  const timed = [];
  let t = start;
  for (let j = 0; j < words.length; j++) {
    const dur = ((end - start) * weights[j]) / wSum;
    timed.push({ w: norm(words[j]), startSec: t, endSec: t + dur });
    t += dur;
  }

  const localFrame = (sec) => Math.round((sec - start) * FPS);
  const find = (target) => {
    if (!target) return null;
    const hit = timed.find((x) => x.w === target);
    return hit ? localFrame(hit.startSec) : null;
  };

  const lastEnd = timed.at(-1).endSec;
  const exitStart = Math.min(localFrame(lastEnd), durationInFrames - EXIT_DUR);

  sceneSync.push({
    durationInFrames,
    accentFlash: find(TARGETS[i].flash),
    footerFlash: find(TARGETS[i].footer),
    ctaLand: find(TARGETS[i].cta),
    exitStart,
  });
}

const totalFrames = cumFrameStops.at(-1);

const ts = `// GENERATED by scripts/sync.mjs — do not edit by hand.
// Per-scene durations + accent-word frames derived from public/voiceover.mp3.
export const FPS = ${FPS};
export const TOTAL_FRAMES = ${totalFrames};

export type SceneSync = {
  durationInFrames: number;
  accentFlash: number | null; // local frame the headline accent word is spoken
  footerFlash: number | null; // local frame the footer accent word is spoken
  ctaLand: number | null; // local frame the CTA phrase begins
  exitStart: number; // local frame the exit begins (last word finishing)
};

export const SCENE_SYNC: SceneSync[] = ${JSON.stringify(sceneSync, null, 2)};
`;
fs.writeFileSync(path.join(cwd, "src", "sync.ts"), ts);

console.log("duration", durationSec.toFixed(2), "totalFrames", totalFrames);
console.log("cuts(s):", cuts.map((c) => c.toFixed(2)).join(", "));
console.table(sceneSync);
