// GENERATED by scripts/align.mjs — do not edit by hand.
// Scene frame durations synced to public/voiceover.mp3 (30fps).
export const FPS = 30;
export const SCENE_FRAMES = [214, 152, 218, 192] as const;
export const TOTAL_FRAMES = 776;
