// GENERATED by scripts/sync.mjs — do not edit by hand.
// Per-scene durations + accent-word frames derived from public/voiceover.mp3.
export const FPS = 30;
export const TOTAL_FRAMES = 776;

export type SceneSync = {
  durationInFrames: number;
  accentFlash: number | null; // local frame the headline accent word is spoken
  footerFlash: number | null; // local frame the footer accent word is spoken
  ctaLand: number | null; // local frame the CTA phrase begins
  exitStart: number; // local frame the exit begins (last word finishing)
};

export const SCENE_SYNC: SceneSync[] = [
  {
    "durationInFrames": 214,
    "accentFlash": 37,
    "footerFlash": null,
    "ctaLand": null,
    "exitStart": 206
  },
  {
    "durationInFrames": 152,
    "accentFlash": 42,
    "footerFlash": null,
    "ctaLand": null,
    "exitStart": 144
  },
  {
    "durationInFrames": 218,
    "accentFlash": 53,
    "footerFlash": 106,
    "ctaLand": null,
    "exitStart": 210
  },
  {
    "durationInFrames": 192,
    "accentFlash": 76,
    "footerFlash": null,
    "ctaLand": 139,
    "exitStart": 184
  }
];
