// GENERATED by scripts/sync.mjs — do not edit by hand.
// Per-scene durations + accent-word frames derived from public/voiceover.mp3.
export const FPS = 30;
export const TOTAL_FRAMES = 776;

export type Word = { t: string; s: number; e: number }; // display token + local start/end frame

export type SceneSync = {
  durationInFrames: number;
  accentFlash: number | null; // local frame the headline accent word is spoken
  ctaLand: number | null; // local frame the CTA phrase begins
  exitStart: number; // local frame the exit begins (last word finishing)
  words: Word[]; // spoken script for this scene, word-level timed (karaoke)
};

export const SCENE_SYNC: SceneSync[] = [
  {
    "durationInFrames": 165,
    "accentFlash": 0,
    "ctaLand": null,
    "exitStart": 157,
    "words": [
      {
        "t": "Showing",
        "s": 0,
        "e": 18
      },
      {
        "t": "up",
        "s": 18,
        "e": 24
      },
      {
        "t": "is",
        "s": 24,
        "e": 29
      },
      {
        "t": "easy.",
        "s": 29,
        "e": 44
      },
      {
        "t": "This",
        "s": 44,
        "e": 55
      },
      {
        "t": "is",
        "s": 55,
        "e": 60
      },
      {
        "t": "what",
        "s": 60,
        "e": 71
      },
      {
        "t": "actually",
        "s": 71,
        "e": 91
      },
      {
        "t": "happens",
        "s": 91,
        "e": 110
      },
      {
        "t": "inside",
        "s": 110,
        "e": 125
      },
      {
        "t": "a",
        "s": 125,
        "e": 131
      },
      {
        "t": "real",
        "s": 131,
        "e": 141
      },
      {
        "t": "session.",
        "s": 141,
        "e": 165
      }
    ]
  },
  {
    "durationInFrames": 201,
    "accentFlash": 50,
    "ctaLand": null,
    "exitStart": 193,
    "words": [
      {
        "t": "First,",
        "s": 0,
        "e": 17
      },
      {
        "t": "we",
        "s": 17,
        "e": 22
      },
      {
        "t": "watch",
        "s": 22,
        "e": 35
      },
      {
        "t": "how",
        "s": 35,
        "e": 42
      },
      {
        "t": "you",
        "s": 42,
        "e": 50
      },
      {
        "t": "move",
        "s": 50,
        "e": 60
      },
      {
        "t": "mobility,",
        "s": 60,
        "e": 85
      },
      {
        "t": "strength,",
        "s": 85,
        "e": 110
      },
      {
        "t": "anything",
        "s": 110,
        "e": 129
      },
      {
        "t": "that",
        "s": 129,
        "e": 139
      },
      {
        "t": "needs",
        "s": 139,
        "e": 152
      },
      {
        "t": "work",
        "s": 152,
        "e": 162
      },
      {
        "t": "before",
        "s": 162,
        "e": 177
      },
      {
        "t": "we",
        "s": 177,
        "e": 182
      },
      {
        "t": "load",
        "s": 182,
        "e": 192
      },
      {
        "t": "up.",
        "s": 192,
        "e": 202
      }
    ]
  },
  {
    "durationInFrames": 218,
    "accentFlash": 41,
    "ctaLand": null,
    "exitStart": 210,
    "words": [
      {
        "t": "Then",
        "s": 0,
        "e": 10
      },
      {
        "t": "every",
        "s": 10,
        "e": 23
      },
      {
        "t": "rep",
        "s": 23,
        "e": 31
      },
      {
        "t": "gets",
        "s": 31,
        "e": 41
      },
      {
        "t": "watched.",
        "s": 41,
        "e": 64
      },
      {
        "t": "Not",
        "s": 64,
        "e": 72
      },
      {
        "t": "just",
        "s": 72,
        "e": 82
      },
      {
        "t": "counted.",
        "s": 82,
        "e": 105
      },
      {
        "t": "Form",
        "s": 105,
        "e": 115
      },
      {
        "t": "fixed",
        "s": 115,
        "e": 128
      },
      {
        "t": "in",
        "s": 128,
        "e": 133
      },
      {
        "t": "real",
        "s": 133,
        "e": 144
      },
      {
        "t": "time,",
        "s": 144,
        "e": 159
      },
      {
        "t": "the",
        "s": 159,
        "e": 167
      },
      {
        "t": "part",
        "s": 167,
        "e": 177
      },
      {
        "t": "you",
        "s": 177,
        "e": 185
      },
      {
        "t": "can't",
        "s": 185,
        "e": 195
      },
      {
        "t": "do",
        "s": 195,
        "e": 200
      },
      {
        "t": "alone.",
        "s": 200,
        "e": 218
      }
    ]
  },
  {
    "durationInFrames": 192,
    "accentFlash": 66,
    "ctaLand": 140,
    "exitStart": 184,
    "words": [
      {
        "t": "Progress",
        "s": 0,
        "e": 20
      },
      {
        "t": "gets",
        "s": 20,
        "e": 30
      },
      {
        "t": "logged,",
        "s": 30,
        "e": 49
      },
      {
        "t": "the",
        "s": 49,
        "e": 57
      },
      {
        "t": "plan",
        "s": 57,
        "e": 66
      },
      {
        "t": "evolves",
        "s": 66,
        "e": 84
      },
      {
        "t": "as",
        "s": 84,
        "e": 89
      },
      {
        "t": "you",
        "s": 89,
        "e": 96
      },
      {
        "t": "get",
        "s": 96,
        "e": 103
      },
      {
        "t": "stronger.",
        "s": 103,
        "e": 128
      },
      {
        "t": "Ready?",
        "s": 128,
        "e": 140
      },
      {
        "t": "DM",
        "s": 140,
        "e": 145
      },
      {
        "t": "or",
        "s": 145,
        "e": 150
      },
      {
        "t": "WhatsApp",
        "s": 150,
        "e": 170
      },
      {
        "t": "to",
        "s": 170,
        "e": 175
      },
      {
        "t": "start.",
        "s": 175,
        "e": 192
      }
    ]
  }
];
